fixtures:
  symlinks:
    userprefs: "#{source_dir}"
  forge_modules:
    chocolatey:
      repo: "puppetlabs/chocolatey"
      ref: "5.2.1"
    stdlib:
      repo: "puppetlabs/stdlib"
      ref: "6.6.0"
    registry:
      repo: "puppetlabs/registry"
      ref: "3.2.0"
    epel:
      repo: "stahnma/epel"
      ref: "2.0.0"
    yumrepo:
      repo: "puppetlabs/yumrepo_core"
      ref: "1.0.7"